### ISSUE TITLE
CentOS redhat-lsb-core dependency

### ISSUE THREAD

**Issue by ralexx** [ddierickx/dtop#1]
Adding the `dtop_0.1_SNAPSHOT-linux-amd64.rpm` in CentOS 6.5 results in

```
error: Failed dependencies:
    redhat-lsb-core is needed by dtop-0.1_SNAPSHOT-1.x86_64
```

Installing that package in yum solves it. Works well and looks good.
Might also be worth noting in the readme that the CentOS package installs to /usr/bin and the default.json to /etc/dtop.

**Comment by ddierickx** [comment]
Hi ralexx, thanks a lot for your feedback! I tested this using:

```
sudo yum localinstall dtop_0.1_SNAPSHOT-linux-amd64.rpm
```

and that seems to install the dependency `redhat-lsb-core` as well? Can you tell me how you tried installing the rpm?

Good point on the install locations, I added that to the readme as you suggested.

**Comment by ralexx** [comment]
Fair point, out of habit I installed your package with rpm not yum. Thanks for listening and setting me straight. You've got a visually appealing solution that works as advertised. Nice!
