### ISSUE TITLE
deb package wants to remove /usr/local/share

### ISSUE THREAD

**Issue by lukecyca** [ddierickx/dtop#2]
I tried this out on a Debian 7 machine. It's works as advertised and looks great. Very nice work!

When I went to uninstall it, I got this warning which might indicate a problem with your .deb package:

```
root@vps3:~# dpkg --remove dtop
(Reading database ... 68484 files and directories currently installed.)
Removing dtop ...
dpkg: warning: while removing dtop, directory '/usr/local/share' not empty so not removed
```

**Comment by ddierickx** [comment]
Thanks for reporting this issue.

I noticed the following things while examining:
- no data seemed to be removed after a package removal, when uninstalling the service is now stopped and all data is removed.
- the architecture for i386 packages was not set.
- /usr/local/share was an incorrect location for those files, they are now moved to /var/dtop
